# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: a8d74cee
    url: /
    weight: 10
  - name: Papers
    identifier: 362ea7d9
    url: /#papers
    weight: 20
  - name: Education & Experience
    identifier: education-experience
    url: /experience
    weight: 30
